package by.anton.xxssd.entity;

public enum HematotropicSubGroups {
    ANTIPLATELET_AGENTS,
    ANTICOUGULANTS,
    SUBSTITUTES_BLOOD,
    FIBRINOLYSIS_INHIBITORS,
    COAGULATION_FACTORS,
    HEMATOPOIESIS_STIMULANTS

}
