package by.anton.xxssd.entity;

public enum NervousSystemTypes {
    CENTRAL_NERVOUS_SYSTEM,
    PERIPHERAL_NERVOUS_SYSTEM,
    AFFERENT_DIVISION,
    EFFERENT_DIVISION,
    AUTONOMIC_NERVOUS_SYSTEM,
    SOMATIC_NERVOUS_SYSTEM,
    SYMPATHETIC_DIVISION,
    PARASYMPATHETIC_DIVISION
}
